// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package projectdriver

import (
	"context"
	"errors"
	"github.com/anhntbk08/gateway/internal/app/tmbridgev2/service/project"
	entity "github.com/anhntbk08/gateway/internal/app/tmbridgev2/store/entity"
	bson "github.com/globalsign/mgo/bson"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	Create endpoint.Endpoint
	Delete endpoint.Endpoint
	List   endpoint.Endpoint
	Update endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service project.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{
		Create: kitxendpoint.OperationNameMiddleware("project.Create")(mw(MakeCreateEndpoint(service))),
		Delete: kitxendpoint.OperationNameMiddleware("project.Delete")(mw(MakeDeleteEndpoint(service))),
		List:   kitxendpoint.OperationNameMiddleware("project.List")(mw(MakeListEndpoint(service))),
		Update: kitxendpoint.OperationNameMiddleware("project.Update")(mw(MakeUpdateEndpoint(service))),
	}
}

// CreateRequest is a request struct for Create endpoint.
type CreateRequest struct {
	Name string
}

// CreateResponse is a response struct for Create endpoint.
type CreateResponse struct {
	Project entity.Project
	Err     error
}

func (r CreateResponse) Failed() error {
	return r.Err
}

// MakeCreateEndpoint returns an endpoint for the matching method of the underlying service.
func MakeCreateEndpoint(service project.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(CreateRequest)

		project, err := service.Create(ctx, req.Name)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return CreateResponse{
					Err:     err,
					Project: project,
				}, err
			}

			return CreateResponse{
				Err:     err,
				Project: project,
			}, nil
		}

		return CreateResponse{Project: project}, nil
	}
}

// DeleteRequest is a request struct for Delete endpoint.
type DeleteRequest struct {
	Id bson.ObjectId
}

// DeleteResponse is a response struct for Delete endpoint.
type DeleteResponse struct {
	Err error
}

func (r DeleteResponse) Failed() error {
	return r.Err
}

// MakeDeleteEndpoint returns an endpoint for the matching method of the underlying service.
func MakeDeleteEndpoint(service project.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(DeleteRequest)

		err := service.Delete(ctx, req.Id)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return DeleteResponse{Err: err}, err
			}

			return DeleteResponse{Err: err}, nil
		}

		return DeleteResponse{}, nil
	}
}

// ListRequest is a request struct for List endpoint.
type ListRequest struct{}

// ListResponse is a response struct for List endpoint.
type ListResponse struct {
	Projects []entity.Project
	Err      error
}

func (r ListResponse) Failed() error {
	return r.Err
}

// MakeListEndpoint returns an endpoint for the matching method of the underlying service.
func MakeListEndpoint(service project.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		projects, err := service.List(ctx)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return ListResponse{
					Err:      err,
					Projects: projects,
				}, err
			}

			return ListResponse{
				Err:      err,
				Projects: projects,
			}, nil
		}

		return ListResponse{Projects: projects}, nil
	}
}

// UpdateRequest is a request struct for Update endpoint.
type UpdateRequest struct {
	Project entity.Project
}

// UpdateResponse is a response struct for Update endpoint.
type UpdateResponse struct {
	Err error
}

func (r UpdateResponse) Failed() error {
	return r.Err
}

// MakeUpdateEndpoint returns an endpoint for the matching method of the underlying service.
func MakeUpdateEndpoint(service project.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(UpdateRequest)

		err := service.Update(ctx, req.Project)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return UpdateResponse{Err: err}, err
			}

			return UpdateResponse{Err: err}, nil
		}

		return UpdateResponse{}, nil
	}
}
