// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: bridge/v1/auth.proto

package gateway

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RequestTokenRequest) Reset() {
	*x = RequestTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_v1_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTokenRequest) ProtoMessage() {}

func (x *RequestTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTokenRequest.ProtoReflect.Descriptor instead.
func (*RequestTokenRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTokenRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RequestTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RequestTokenResponse) Reset() {
	*x = RequestTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_v1_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTokenResponse) ProtoMessage() {}

func (x *RequestTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTokenResponse.ProtoReflect.Descriptor instead.
func (*RequestTokenResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RequestTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthServiceLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AuthServiceLoginRequest) Reset() {
	*x = AuthServiceLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_v1_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthServiceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceLoginRequest) ProtoMessage() {}

func (x *AuthServiceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthServiceLoginRequest) Descriptor() ([]byte, []int) {
	return file_bridge_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthServiceLoginRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AuthServiceLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AuthServiceLoginResponse) Reset() {
	*x = AuthServiceLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridge_v1_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthServiceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceLoginResponse) ProtoMessage() {}

func (x *AuthServiceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_v1_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthServiceLoginResponse) Descriptor() ([]byte, []int) {
	return file_bridge_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthServiceLoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bridge_v1_auth_proto protoreflect.FileDescriptor

var file_bridge_v1_auth_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x2f, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x2c, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x33, 0x0a, 0x17, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x34, 0x0a, 0x18, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xb4, 0x01, 0x0a, 0x0b,
	0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x22, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bridge_v1_auth_proto_rawDescOnce sync.Once
	file_bridge_v1_auth_proto_rawDescData = file_bridge_v1_auth_proto_rawDesc
)

func file_bridge_v1_auth_proto_rawDescGZIP() []byte {
	file_bridge_v1_auth_proto_rawDescOnce.Do(func() {
		file_bridge_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridge_v1_auth_proto_rawDescData)
	})
	return file_bridge_v1_auth_proto_rawDescData
}

var file_bridge_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bridge_v1_auth_proto_goTypes = []interface{}{
	(*RequestTokenRequest)(nil),      // 0: bridge.v1.RequestTokenRequest
	(*RequestTokenResponse)(nil),     // 1: bridge.v1.RequestTokenResponse
	(*AuthServiceLoginRequest)(nil),  // 2: bridge.v1.AuthServiceLoginRequest
	(*AuthServiceLoginResponse)(nil), // 3: bridge.v1.AuthServiceLoginResponse
}
var file_bridge_v1_auth_proto_depIdxs = []int32{
	0, // 0: bridge.v1.AuthService.RequestToken:input_type -> bridge.v1.RequestTokenRequest
	2, // 1: bridge.v1.AuthService.Login:input_type -> bridge.v1.AuthServiceLoginRequest
	1, // 2: bridge.v1.AuthService.RequestToken:output_type -> bridge.v1.RequestTokenResponse
	3, // 3: bridge.v1.AuthService.Login:output_type -> bridge.v1.AuthServiceLoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridge_v1_auth_proto_init() }
func file_bridge_v1_auth_proto_init() {
	if File_bridge_v1_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bridge_v1_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_v1_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_v1_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthServiceLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridge_v1_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthServiceLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridge_v1_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_v1_auth_proto_goTypes,
		DependencyIndexes: file_bridge_v1_auth_proto_depIdxs,
		MessageInfos:      file_bridge_v1_auth_proto_msgTypes,
	}.Build()
	File_bridge_v1_auth_proto = out.File
	file_bridge_v1_auth_proto_rawDesc = nil
	file_bridge_v1_auth_proto_goTypes = nil
	file_bridge_v1_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	RequestToken(ctx context.Context, in *RequestTokenRequest, opts ...grpc.CallOption) (*RequestTokenResponse, error)
	Login(ctx context.Context, in *AuthServiceLoginRequest, opts ...grpc.CallOption) (*AuthServiceLoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RequestToken(ctx context.Context, in *RequestTokenRequest, opts ...grpc.CallOption) (*RequestTokenResponse, error) {
	out := new(RequestTokenResponse)
	err := c.cc.Invoke(ctx, "/bridge.v1.AuthService/RequestToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthServiceLoginRequest, opts ...grpc.CallOption) (*AuthServiceLoginResponse, error) {
	out := new(AuthServiceLoginResponse)
	err := c.cc.Invoke(ctx, "/bridge.v1.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	RequestToken(context.Context, *RequestTokenRequest) (*RequestTokenResponse, error)
	Login(context.Context, *AuthServiceLoginRequest) (*AuthServiceLoginResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) RequestToken(context.Context, *RequestTokenRequest) (*RequestTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestToken not implemented")
}
func (*UnimplementedAuthServiceServer) Login(context.Context, *AuthServiceLoginRequest) (*AuthServiceLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_RequestToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RequestToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridge.v1.AuthService/RequestToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RequestToken(ctx, req.(*RequestTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthServiceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridge.v1.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthServiceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestToken",
			Handler:    _AuthService_RequestToken_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/v1/auth.proto",
}
