// Code generated by protoc-gen-kit. DO NOT EDIT.

package gateway

import (
	"context"
	kitgrpc "github.com/go-kit/kit/transport/grpc"
)

type ProjectServiceKitServer struct {
	*UnimplementedProjectServiceServer

	CreateHandler kitgrpc.Handler
	UpdateHandler kitgrpc.Handler
	DeleteHandler kitgrpc.Handler
}

func (s ProjectServiceKitServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	_, resp, err := s.CreateHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*CreateResponse), nil
}
func (s ProjectServiceKitServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	_, resp, err := s.UpdateHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*UpdateResponse), nil
}
func (s ProjectServiceKitServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	_, resp, err := s.DeleteHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*DeleteResponse), nil
}
