// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package projectdriver

import (
	"context"
	"errors"
	"github.com/anhntbk08/gateway/internal/app/gateway/bridge/service/project"
	entity "github.com/anhntbk08/gateway/internal/app/gateway/store/entity"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	Create endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service project.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{Create: kitxendpoint.OperationNameMiddleware("project.Create")(mw(MakeCreateEndpoint(service)))}
}

// CreateRequest is a request struct for Create endpoint.
type CreateRequest struct {
	Name string
	User string
}

// CreateResponse is a response struct for Create endpoint.
type CreateResponse struct {
	Project entity.Project
	Err     error
}

func (r CreateResponse) Failed() error {
	return r.Err
}

// MakeCreateEndpoint returns an endpoint for the matching method of the underlying service.
func MakeCreateEndpoint(service project.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(CreateRequest)

		project, err := service.Create(ctx, req.Name, req.User)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return CreateResponse{
					Err:     err,
					Project: project,
				}, err
			}

			return CreateResponse{
				Err:     err,
				Project: project,
			}, nil
		}

		return CreateResponse{Project: project}, nil
	}
}
