// Code generated by protoc-gen-kit. DO NOT EDIT.

package gateway

import (
	"context"
	kitgrpc "github.com/go-kit/kit/transport/grpc"
)

type AuthServiceKitServer struct {
	*UnimplementedAuthServiceServer

	RequestTokenHandler kitgrpc.Handler
	LoginHandler        kitgrpc.Handler
}

func (s AuthServiceKitServer) RequestToken(ctx context.Context, req *RequestTokenRequest) (*RequestTokenResponse, error) {
	_, resp, err := s.RequestTokenHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*RequestTokenResponse), nil
}
func (s AuthServiceKitServer) Login(ctx context.Context, req *AuthServiceLoginRequest) (*AuthServiceLoginResponse, error) {
	_, resp, err := s.LoginHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*AuthServiceLoginResponse), nil
}
