// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package addressdriver

import (
	"context"
	"errors"
	"github.com/anhntbk08/gateway/internal/app/tmbridgev2/service/address"
	entity "github.com/anhntbk08/gateway/internal/app/tmbridgev2/store/entity"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	IsIsssueBy endpoint.Endpoint
	Issue      endpoint.Endpoint
	List       endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service address.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{
		IsIsssueBy: kitxendpoint.OperationNameMiddleware("address.IsIsssueBy")(mw(MakeIsIsssueByEndpoint(service))),
		Issue:      kitxendpoint.OperationNameMiddleware("address.Issue")(mw(MakeIssueEndpoint(service))),
		List:       kitxendpoint.OperationNameMiddleware("address.List")(mw(MakeListEndpoint(service))),
	}
}

// IsIsssueByRequest is a request struct for IsIsssueBy endpoint.
type IsIsssueByRequest struct {
	Address string
}

// IsIsssueByResponse is a response struct for IsIsssueBy endpoint.
type IsIsssueByResponse struct {
	R0  bool
	Err error
}

func (r IsIsssueByResponse) Failed() error {
	return r.Err
}

// MakeIsIsssueByEndpoint returns an endpoint for the matching method of the underlying service.
func MakeIsIsssueByEndpoint(service address.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(IsIsssueByRequest)

		r0, err := service.IsIsssueBy(ctx, req.Address)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return IsIsssueByResponse{
					Err: err,
					R0:  r0,
				}, err
			}

			return IsIsssueByResponse{
				Err: err,
				R0:  r0,
			}, nil
		}

		return IsIsssueByResponse{R0: r0}, nil
	}
}

// IssueRequest is a request struct for Issue endpoint.
type IssueRequest struct {
	IssueRequest address.IssueRequest
}

// IssueResponse is a response struct for Issue endpoint.
type IssueResponse struct {
	R0  entity.Address
	Err error
}

func (r IssueResponse) Failed() error {
	return r.Err
}

// MakeIssueEndpoint returns an endpoint for the matching method of the underlying service.
func MakeIssueEndpoint(service address.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(IssueRequest)

		r0, err := service.Issue(ctx, req.IssueRequest)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return IssueResponse{
					Err: err,
					R0:  r0,
				}, err
			}

			return IssueResponse{
				Err: err,
				R0:  r0,
			}, nil
		}

		return IssueResponse{R0: r0}, nil
	}
}

// ListRequest is a request struct for List endpoint.
type ListRequest struct {
	ListRequest address.ListRequest
}

// ListResponse is a response struct for List endpoint.
type ListResponse struct {
	R0  []entity.Address
	Err error
}

func (r ListResponse) Failed() error {
	return r.Err
}

// MakeListEndpoint returns an endpoint for the matching method of the underlying service.
func MakeListEndpoint(service address.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(ListRequest)

		r0, err := service.List(ctx, req.ListRequest)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return ListResponse{
					Err: err,
					R0:  r0,
				}, err
			}

			return ListResponse{
				Err: err,
				R0:  r0,
			}, nil
		}

		return ListResponse{R0: r0}, nil
	}
}
