// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package authdriver

import (
	"context"
	"errors"
	"github.com/anhntbk08/gateway/internal/app/gateway/bridge/service/auth"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	RequestToken endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service auth.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{RequestToken: kitxendpoint.OperationNameMiddleware("auth.RequestToken")(mw(MakeRequestTokenEndpoint(service)))}
}

// RequestTokenRequest is a request struct for RequestToken endpoint.
type RequestTokenRequest struct {
	Request auth.RqTokenData
}

// RequestTokenResponse is a response struct for RequestToken endpoint.
type RequestTokenResponse struct {
	Token auth.Token
	Err   error
}

func (r RequestTokenResponse) Failed() error {
	return r.Err
}

// MakeRequestTokenEndpoint returns an endpoint for the matching method of the underlying service.
func MakeRequestTokenEndpoint(service auth.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(RequestTokenRequest)

		token, err := service.RequestToken(ctx, req.Request)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return RequestTokenResponse{
					Err:   err,
					Token: token,
				}, err
			}

			return RequestTokenResponse{
				Err:   err,
				Token: token,
			}, nil
		}

		return RequestTokenResponse{Token: token}, nil
	}
}
