// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package servicedriver

import (
	"context"
	"errors"
	"github.com/anhntbk08/gateway/internal/app/gateway/bridge/service"
	"github.com/go-kit/kit/endpoint"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
)

// endpointError identifies an error that should be returned as an endpoint error.
type endpointError interface {
	EndpointError() bool
}

// serviceError identifies an error that should be returned as a service error.
type serviceError interface {
	ServiceError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	AddItem endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service service.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{AddItem: kitxendpoint.OperationNameMiddleware("service.AddItem")(mw(MakeAddItemEndpoint(service)))}
}

// AddItemRequest is a request struct for AddItem endpoint.
type AddItemRequest struct {
	NewItem service.NewItem
}

// AddItemResponse is a response struct for AddItem endpoint.
type AddItemResponse struct {
	Item service.Item
	Err  error
}

func (r AddItemResponse) Failed() error {
	return r.Err
}

// MakeAddItemEndpoint returns an endpoint for the matching method of the underlying service.
func MakeAddItemEndpoint(service service.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(AddItemRequest)

		item, err := service.AddItem(ctx, req.NewItem)

		if err != nil {
			if serviceErr := serviceError(nil); errors.As(err, &serviceErr) && serviceErr.ServiceError() {
				return AddItemResponse{
					Err:  err,
					Item: item,
				}, nil
			}

			return AddItemResponse{
				Err:  err,
				Item: item,
			}, err
		}

		return AddItemResponse{Item: item}, nil
	}
}
