// Code generated by protoc-gen-kit. DO NOT EDIT.

package gateway

import (
	"context"
	kitgrpc "github.com/go-kit/kit/transport/grpc"
)

type AddressServiceKitServer struct {
	*UnimplementedAddressServiceServer

	IssueHandler      kitgrpc.Handler
	ListHandler       kitgrpc.Handler
	IsIsssueByHandler kitgrpc.Handler
}

func (s AddressServiceKitServer) Issue(ctx context.Context, req *IssueRequest) (*IssueResponse, error) {
	_, resp, err := s.IssueHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*IssueResponse), nil
}
func (s AddressServiceKitServer) List(ctx context.Context, req *AddressServiceListRequest) (*AddressServiceListResponse, error) {
	_, resp, err := s.ListHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*AddressServiceListResponse), nil
}
func (s AddressServiceKitServer) IsIsssueBy(ctx context.Context, req *IsIsssueByRequest) (*IsIsssueByResponse, error) {
	_, resp, err := s.IsIsssueByHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*IsIsssueByResponse), nil
}
