// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: gateway/v1/swap_transaction.proto

package gateway

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SwapTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber   string `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	CoinType      string `protobuf:"bytes,3,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	From          string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Confirmations string `protobuf:"bytes,8,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Status        string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ScId          string `protobuf:"bytes,10,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
}

func (x *SwapTransaction) Reset() {
	*x = SwapTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapTransaction) ProtoMessage() {}

func (x *SwapTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapTransaction.ProtoReflect.Descriptor instead.
func (*SwapTransaction) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *SwapTransaction) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *SwapTransaction) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SwapTransaction) GetCoinType() string {
	if x != nil {
		return x.CoinType
	}
	return ""
}

func (x *SwapTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SwapTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SwapTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SwapTransaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SwapTransaction) GetConfirmations() string {
	if x != nil {
		return x.Confirmations
	}
	return ""
}

func (x *SwapTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwapTransaction) GetScId() string {
	if x != nil {
		return x.ScId
	}
	return ""
}

type SwapTransactionRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Intx      *SwapTransaction `protobuf:"bytes,1,opt,name=intx,proto3" json:"intx,omitempty"`
	Outtx     *SwapTransaction `protobuf:"bytes,2,opt,name=outtx,proto3" json:"outtx,omitempty"`
	CreatedAt string           `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string           `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *SwapTransactionRecord) Reset() {
	*x = SwapTransactionRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapTransactionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapTransactionRecord) ProtoMessage() {}

func (x *SwapTransactionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapTransactionRecord.ProtoReflect.Descriptor instead.
func (*SwapTransactionRecord) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *SwapTransactionRecord) GetIntx() *SwapTransaction {
	if x != nil {
		return x.Intx
	}
	return nil
}

func (x *SwapTransactionRecord) GetOuttx() *SwapTransaction {
	if x != nil {
		return x.Outtx
	}
	return nil
}

func (x *SwapTransactionRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SwapTransactionRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSwapHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin      string `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Limit     uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page      uint64 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetSwapHistoryRequest) Reset() {
	*x = GetSwapHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapHistoryRequest) ProtoMessage() {}

func (x *GetSwapHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSwapHistoryRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetSwapHistoryRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GetSwapHistoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetSwapHistoryRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSwapHistoryRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSwapHistoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetSwapHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*SwapTransactionRecord `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total        uint64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetSwapHistoryResponse) Reset() {
	*x = GetSwapHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapHistoryResponse) ProtoMessage() {}

func (x *GetSwapHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSwapHistoryResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetSwapHistoryResponse) GetTransactions() []*SwapTransactionRecord {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetSwapHistoryResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLastestDepositRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin string `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Tomo string `protobuf:"bytes,2,opt,name=tomo,proto3" json:"tomo,omitempty"`
}

func (x *GetLastestDepositRequest) Reset() {
	*x = GetLastestDepositRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastestDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastestDepositRequest) ProtoMessage() {}

func (x *GetLastestDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastestDepositRequest.ProtoReflect.Descriptor instead.
func (*GetLastestDepositRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastestDepositRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GetLastestDepositRequest) GetTomo() string {
	if x != nil {
		return x.Tomo
	}
	return ""
}

type GetLastestDepositResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin        string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Tomo        string                 `protobuf:"bytes,2,opt,name=tomo,proto3" json:"tomo,omitempty"`
	Transaction *SwapTransactionRecord `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *GetLastestDepositResponse) Reset() {
	*x = GetLastestDepositResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastestDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastestDepositResponse) ProtoMessage() {}

func (x *GetLastestDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastestDepositResponse.ProtoReflect.Descriptor instead.
func (*GetLastestDepositResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetLastestDepositResponse) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GetLastestDepositResponse) GetTomo() string {
	if x != nil {
		return x.Tomo
	}
	return ""
}

func (x *GetLastestDepositResponse) GetTransaction() *SwapTransactionRecord {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetLastestWithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin string `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Tomo string `protobuf:"bytes,2,opt,name=tomo,proto3" json:"tomo,omitempty"`
}

func (x *GetLastestWithdrawRequest) Reset() {
	*x = GetLastestWithdrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastestWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastestWithdrawRequest) ProtoMessage() {}

func (x *GetLastestWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastestWithdrawRequest.ProtoReflect.Descriptor instead.
func (*GetLastestWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastestWithdrawRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GetLastestWithdrawRequest) GetTomo() string {
	if x != nil {
		return x.Tomo
	}
	return ""
}

type GetLastestWithdrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin        string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Tomo        string                 `protobuf:"bytes,2,opt,name=tomo,proto3" json:"tomo,omitempty"`
	Transaction *SwapTransactionRecord `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *GetLastestWithdrawResponse) Reset() {
	*x = GetLastestWithdrawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_v1_swap_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastestWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastestWithdrawResponse) ProtoMessage() {}

func (x *GetLastestWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_swap_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastestWithdrawResponse.ProtoReflect.Descriptor instead.
func (*GetLastestWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_swap_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastestWithdrawResponse) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *GetLastestWithdrawResponse) GetTomo() string {
	if x != nil {
		return x.Tomo
	}
	return ""
}

func (x *GetLastestWithdrawResponse) GetTransaction() *SwapTransactionRecord {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_gateway_v1_swap_transaction_proto protoreflect.FileDescriptor

var file_gateway_v1_swap_transaction_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x77, 0x61,
	0x70, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x22,
	0x97, 0x02, 0x0a, 0x0f, 0x53, 0x77, 0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x15, 0x53, 0x77,
	0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x77, 0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x69, 0x6e, 0x74, 0x78, 0x12, 0x31, 0x0a, 0x05, 0x6f, 0x75, 0x74, 0x74, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x77, 0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x6f, 0x75, 0x74, 0x74, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61,
	0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x75, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77,
	0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x42, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x6d,
	0x6f, 0x12, 0x43, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73,
	0x74, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x6f, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f,
	0x6d, 0x6f, 0x12, 0x43, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xba, 0x02, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x21, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x77, 0x61, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x24,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x12, 0x25, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x65,
	0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_v1_swap_transaction_proto_rawDescOnce sync.Once
	file_gateway_v1_swap_transaction_proto_rawDescData = file_gateway_v1_swap_transaction_proto_rawDesc
)

func file_gateway_v1_swap_transaction_proto_rawDescGZIP() []byte {
	file_gateway_v1_swap_transaction_proto_rawDescOnce.Do(func() {
		file_gateway_v1_swap_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_v1_swap_transaction_proto_rawDescData)
	})
	return file_gateway_v1_swap_transaction_proto_rawDescData
}

var file_gateway_v1_swap_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateway_v1_swap_transaction_proto_goTypes = []interface{}{
	(*SwapTransaction)(nil),            // 0: gateway.v1.SwapTransaction
	(*SwapTransactionRecord)(nil),      // 1: gateway.v1.SwapTransactionRecord
	(*GetSwapHistoryRequest)(nil),      // 2: gateway.v1.GetSwapHistoryRequest
	(*GetSwapHistoryResponse)(nil),     // 3: gateway.v1.GetSwapHistoryResponse
	(*GetLastestDepositRequest)(nil),   // 4: gateway.v1.GetLastestDepositRequest
	(*GetLastestDepositResponse)(nil),  // 5: gateway.v1.GetLastestDepositResponse
	(*GetLastestWithdrawRequest)(nil),  // 6: gateway.v1.GetLastestWithdrawRequest
	(*GetLastestWithdrawResponse)(nil), // 7: gateway.v1.GetLastestWithdrawResponse
}
var file_gateway_v1_swap_transaction_proto_depIdxs = []int32{
	0, // 0: gateway.v1.SwapTransactionRecord.intx:type_name -> gateway.v1.SwapTransaction
	0, // 1: gateway.v1.SwapTransactionRecord.outtx:type_name -> gateway.v1.SwapTransaction
	1, // 2: gateway.v1.GetSwapHistoryResponse.transactions:type_name -> gateway.v1.SwapTransactionRecord
	1, // 3: gateway.v1.GetLastestDepositResponse.transaction:type_name -> gateway.v1.SwapTransactionRecord
	1, // 4: gateway.v1.GetLastestWithdrawResponse.transaction:type_name -> gateway.v1.SwapTransactionRecord
	2, // 5: gateway.v1.TransactionService.GetSwapHistory:input_type -> gateway.v1.GetSwapHistoryRequest
	4, // 6: gateway.v1.TransactionService.GetLastestDeposit:input_type -> gateway.v1.GetLastestDepositRequest
	6, // 7: gateway.v1.TransactionService.GetLastestWithdraw:input_type -> gateway.v1.GetLastestWithdrawRequest
	3, // 8: gateway.v1.TransactionService.GetSwapHistory:output_type -> gateway.v1.GetSwapHistoryResponse
	5, // 9: gateway.v1.TransactionService.GetLastestDeposit:output_type -> gateway.v1.GetLastestDepositResponse
	7, // 10: gateway.v1.TransactionService.GetLastestWithdraw:output_type -> gateway.v1.GetLastestWithdrawResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_v1_swap_transaction_proto_init() }
func file_gateway_v1_swap_transaction_proto_init() {
	if File_gateway_v1_swap_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_v1_swap_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwapTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwapTransactionRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSwapHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSwapHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastestDepositRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastestDepositResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastestWithdrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_v1_swap_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastestWithdrawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_v1_swap_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_swap_transaction_proto_goTypes,
		DependencyIndexes: file_gateway_v1_swap_transaction_proto_depIdxs,
		MessageInfos:      file_gateway_v1_swap_transaction_proto_msgTypes,
	}.Build()
	File_gateway_v1_swap_transaction_proto = out.File
	file_gateway_v1_swap_transaction_proto_rawDesc = nil
	file_gateway_v1_swap_transaction_proto_goTypes = nil
	file_gateway_v1_swap_transaction_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetSwapHistory(ctx context.Context, in *GetSwapHistoryRequest, opts ...grpc.CallOption) (*GetSwapHistoryResponse, error)
	GetLastestDeposit(ctx context.Context, in *GetLastestDepositRequest, opts ...grpc.CallOption) (*GetLastestDepositResponse, error)
	GetLastestWithdraw(ctx context.Context, in *GetLastestWithdrawRequest, opts ...grpc.CallOption) (*GetLastestWithdrawResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetSwapHistory(ctx context.Context, in *GetSwapHistoryRequest, opts ...grpc.CallOption) (*GetSwapHistoryResponse, error) {
	out := new(GetSwapHistoryResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.TransactionService/GetSwapHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetLastestDeposit(ctx context.Context, in *GetLastestDepositRequest, opts ...grpc.CallOption) (*GetLastestDepositResponse, error) {
	out := new(GetLastestDepositResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.TransactionService/GetLastestDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetLastestWithdraw(ctx context.Context, in *GetLastestWithdrawRequest, opts ...grpc.CallOption) (*GetLastestWithdrawResponse, error) {
	out := new(GetLastestWithdrawResponse)
	err := c.cc.Invoke(ctx, "/gateway.v1.TransactionService/GetLastestWithdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	GetSwapHistory(context.Context, *GetSwapHistoryRequest) (*GetSwapHistoryResponse, error)
	GetLastestDeposit(context.Context, *GetLastestDepositRequest) (*GetLastestDepositResponse, error)
	GetLastestWithdraw(context.Context, *GetLastestWithdrawRequest) (*GetLastestWithdrawResponse, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) GetSwapHistory(context.Context, *GetSwapHistoryRequest) (*GetSwapHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwapHistory not implemented")
}
func (*UnimplementedTransactionServiceServer) GetLastestDeposit(context.Context, *GetLastestDepositRequest) (*GetLastestDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastestDeposit not implemented")
}
func (*UnimplementedTransactionServiceServer) GetLastestWithdraw(context.Context, *GetLastestWithdrawRequest) (*GetLastestWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastestWithdraw not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_GetSwapHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetSwapHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.TransactionService/GetSwapHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetSwapHistory(ctx, req.(*GetSwapHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetLastestDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastestDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetLastestDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.TransactionService/GetLastestDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetLastestDeposit(ctx, req.(*GetLastestDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetLastestWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastestWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetLastestWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.v1.TransactionService/GetLastestWithdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetLastestWithdraw(ctx, req.(*GetLastestWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSwapHistory",
			Handler:    _TransactionService_GetSwapHistory_Handler,
		},
		{
			MethodName: "GetLastestDeposit",
			Handler:    _TransactionService_GetLastestDeposit_Handler,
		},
		{
			MethodName: "GetLastestWithdraw",
			Handler:    _TransactionService_GetLastestWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/swap_transaction.proto",
}
