// Code generated by protoc-gen-kit. DO NOT EDIT.

package gateway

import (
	"context"
	kitgrpc "github.com/go-kit/kit/transport/grpc"
)

type TransactionServiceKitServer struct {
	*UnimplementedTransactionServiceServer

	GetSwapHistoryHandler     kitgrpc.Handler
	GetLastestDepositHandler  kitgrpc.Handler
	GetLastestWithdrawHandler kitgrpc.Handler
}

func (s TransactionServiceKitServer) GetSwapHistory(ctx context.Context, req *GetSwapHistoryRequest) (*GetSwapHistoryResponse, error) {
	_, resp, err := s.GetSwapHistoryHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*GetSwapHistoryResponse), nil
}
func (s TransactionServiceKitServer) GetLastestDeposit(ctx context.Context, req *GetLastestDepositRequest) (*GetLastestDepositResponse, error) {
	_, resp, err := s.GetLastestDepositHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*GetLastestDepositResponse), nil
}
func (s TransactionServiceKitServer) GetLastestWithdraw(ctx context.Context, req *GetLastestWithdrawRequest) (*GetLastestWithdrawResponse, error) {
	_, resp, err := s.GetLastestWithdrawHandler.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}

	return resp.(*GetLastestWithdrawResponse), nil
}
